FROM node:18-alpine AS build-stage

ARG NODE_ENV=production

ENV NODE_ENV=${NODE_ENV}

WORKDIR /server

COPY package*.json ./

RUN npm ci --only=production

COPY . .

RUN mkdir -p /var/www/html/images/

EXPOSE 3001

CMD ["node", "src/index.js"]
